"""Online data

Revision ID: 5d15b26e8b10
Revises: be16f4eeadd2
Create Date: 2020-04-28 10:13:26.157784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d15b26e8b10'
down_revision = 'be16f4eeadd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'online')
    # ### end Alembic commands ###
